//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductorasResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductorasResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Productoras.App_GlobalResources.ProductorasResources", typeof(ProductorasResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido debe tener entre 3 y 60 caracteres..
        /// </summary>
        public static string apellido_error_minmax {
            get {
                return ResourceManager.GetString("apellido_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos:.
        /// </summary>
        public static string apellido_lbl {
            get {
                return ResourceManager.GetString("apellido_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad:.
        /// </summary>
        public static string ciudad_lbl {
            get {
                return ResourceManager.GetString("ciudad_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción debe tener entre 30 y 255 caracteres..
        /// </summary>
        public static string descripcion_error_minmax {
            get {
                return ResourceManager.GetString("descripcion_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string descripcion_lbl {
            get {
                return ResourceManager.GetString("descripcion_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI debe tener 8 numeros, introducelo en formato 00000000.
        /// </summary>
        public static string dni_error_minmax {
            get {
                return ResourceManager.GetString("dni_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI:.
        /// </summary>
        public static string dni_lbl {
            get {
                return ResourceManager.GetString("dni_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento de identificación introducido no es válido..
        /// </summary>
        public static string dni_noValido {
            get {
                return ResourceManager.GetString("dni_noValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email debe tener al menos 10 caracteres..
        /// </summary>
        public static string email_error_minmax {
            get {
                return ResourceManager.GetString("email_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string email_lbl {
            get {
                return ResourceManager.GetString("email_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es obligatorio..
        /// </summary>
        public static string error_vacio {
            get {
                return ResourceManager.GetString("error_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicio:.
        /// </summary>
        public static string fechaIni_lbl {
            get {
                return ResourceManager.GetString("fechaIni_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo debe ser una imagen JPG o PNG..
        /// </summary>
        public static string foto_error_extension {
            get {
                return ResourceManager.GetString("foto_error_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen de perfil:.
        /// </summary>
        public static string fotoPerfil_lbl {
            get {
                return ResourceManager.GetString("fotoPerfil_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener entre 10 y 60 caracteres..
        /// </summary>
        public static string nombre_error_minmax {
            get {
                return ResourceManager.GetString("nombre_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string nombre_lbl {
            get {
                return ResourceManager.GetString("nombre_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string password_lbl {
            get {
                return ResourceManager.GetString("password_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de proyecto:.
        /// </summary>
        public static string proyecto_tipo_lbl {
            get {
                return ResourceManager.GetString("proyecto_tipo_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener entre 8 y 20 caracteres..
        /// </summary>
        public static string pwd_error_minmax {
            get {
                return ResourceManager.GetString("pwd_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo profesional:.
        /// </summary>
        public static string tipoProfesional_lbl {
            get {
                return ResourceManager.GetString("tipoProfesional_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El teléfono debe tener entre 5 y 20 dígitos..
        /// </summary>
        public static string tlf_error_minmax {
            get {
                return ResourceManager.GetString("tlf_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono:.
        /// </summary>
        public static string tlf_lbl {
            get {
                return ResourceManager.GetString("tlf_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe tener entre 3 y 20 caracteres..
        /// </summary>
        public static string user_error_minmax {
            get {
                return ResourceManager.GetString("user_error_minmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string user_lbl {
            get {
                return ResourceManager.GetString("user_lbl", resourceCulture);
            }
        }
    }
}
