//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comentarios()
        {
            this.ComentariosProyecto = new HashSet<ComentariosProyecto>();
            this.ComentariosUsuario = new HashSet<ComentariosUsuario>();
        }
    
        public int id { get; set; }
        public string titulo_c { get; set; }
        public string comentario_c { get; set; }
        public int autor_xref { get; set; }
        public string ip_c { get; set; }
        public System.DateTime fechaFirst_dt { get; set; }
        public Nullable<System.DateTime> fechaLast_dt { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosProyecto> ComentariosProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosUsuario> ComentariosUsuario { get; set; }
    }
}
