//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class frmProyectosNuevoModel : Proyectos
    {

        /* Nombre */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(10, ErrorMessageResourceName = "nombre_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(60, ErrorMessageResourceName = "nombre_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "nombre_lbl", ResourceType = typeof(ProductorasResources))]
        public new string nombre_c { get; set; }
        /* Descripción */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(50, ErrorMessageResourceName = "descripcion_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(255, ErrorMessageResourceName = "descripcion_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [DataType(DataType.Text)]
        [Display(Name = "descripcion_lbl", ResourceType = typeof(ProductorasResources))]
        public new string descripcion_c { get; set; }
        /* Ciudad */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "ciudad_lbl", ResourceType = typeof(ProductorasResources))]
        public new int ciudad_xref { get; set; }
        /* fechaIni */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "fechaIni_lbl", ResourceType =typeof(ProductorasResources))]
        public new System.DateTime fechaIni_dt { get; set; }
        /* TipoProyecto */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "proyecto_tipo_lbl", ResourceType = typeof(ProductorasResources))]
        public new int tipo_xref { get; set; }
        /* activo */
        public new bool activo_b { get; set; }
    }
}
