//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class frmUsuariosDefineTecnico : UsuariosTecnico
    {

        /* Id */
        public new int id { get; set; }
        /* Nombre */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(3, ErrorMessageResourceName = "nombre_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(20, ErrorMessageResourceName = "nombre_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "nombre_lbl", ResourceType = typeof(ProductorasResources))]
        public new string nombre_c { get; set; }
        /* Apellidos */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(3, ErrorMessageResourceName = "apellido_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(20, ErrorMessageResourceName = "apellido_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "apellido_lbl", ResourceType = typeof(ProductorasResources))]
        public new string apellidos_c { get; set; }
        /* DNI */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(8, ErrorMessageResourceName = "dni_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(8, ErrorMessageResourceName = "dni_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        //[RegularExpression(@"(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))", ErrorMessageResourceName = "dni_noValido", ErrorMessageResourceType = typeof(ProyectoResources))]
        [Display(Name = "dni_lbl", ResourceType = typeof(ProductorasResources))]
        public new string dni_c { get; set; }
        /* Telefono */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(5, ErrorMessageResourceName = "tlf_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(20, ErrorMessageResourceName = "tlf_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "tlf_lbl", ResourceType = typeof(ProductorasResources))]
        public new string telefono_c { get; set; }

        public int categoria { get; set; }
        public int subcategoria { get; set; }

    }
}
