//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class frmUsuariosLoginModel : Usuarios
    {

        /* Id */
        public new int id { get; set; }
        /* Username */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(3, ErrorMessageResourceName = "user_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(20, ErrorMessageResourceName = "email_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [Display(Name = "user_lbl", ResourceType = typeof(ProductorasResources))]
        public new string username_c { get; set; }
        /* Password */
        [Required(ErrorMessageResourceName = "error_vacio", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MinLength(8, ErrorMessageResourceName = "pwd_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [MaxLength(20, ErrorMessageResourceName = "email_error_minmax", ErrorMessageResourceType = typeof(ProductorasResources))]
        [DataType(DataType.Password)]
        [Display(Name = "password_lbl", ResourceType = typeof(ProductorasResources))]
        public new string password { get; set; }
        /* Email */
        public new string email_c { get; set; }
        /* fechaLast */
        public new Nullable<System.DateTime> fechaLast_dt { get; set; }
    }
}
