//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajesProyecto
    {
        public int id { get; set; }
        public int mensaje_xref { get; set; }
        public int proyecto_xref { get; set; }
    
        public virtual Mensajes Mensajes { get; set; }
    }
}
