//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.ComentariosProyecto = new HashSet<ComentariosProyecto>();
            this.ProyectoDemandas = new HashSet<ProyectoDemandas>();
            this.ProyectoFiles = new HashSet<ProyectoFiles>();
            this.ProyectoParticipantes = new HashSet<ProyectoParticipantes>();
        }
    
        public int id { get; set; }
        public string nombre_c { get; set; }
        public string descripcion_c { get; set; }
        public System.DateTime fechaIni_dt { get; set; }
        public Nullable<System.DateTime> fechaLast_dt { get; set; }
        public bool activo_b { get; set; }
        public int tipo_xref { get; set; }
        public int creador_xref { get; set; }
        public Nullable<int> ciudad_xref { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosProyecto> ComentariosProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoDemandas> ProyectoDemandas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoFiles> ProyectoFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoParticipantes> ProyectoParticipantes { get; set; }
        public virtual ProyectosTipo ProyectosTipo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
