//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosTecnico
    {
        public int id { get; set; }
        public string nombre_c { get; set; }
        public string apellidos_c { get; set; }
        public string dni_c { get; set; }
        public string telefono_c { get; set; }
        public int usuario_xref { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
